title: TADS 3 Resources
description: The most powerful and flexible interactive fiction authoring tool, built for programmers.
incremental: true
domain: tads.dev     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://tads.dev  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
lsi: false

defaults:
  - scope:
      path: docs/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/authkit/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/gsg/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/htmltads/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/libref/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/libref/file/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/libref/index/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/libref/object/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/libref/source/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/playkit/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/sysman/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/techman/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/techman/t3spec/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/tourguide/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3/doc/wb/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/extensions/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/learning/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/libref/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/libref/file/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/libref/index/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/libref/message/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/libref/object/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/libref/source/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/manual/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"
  - scope:
      path: docs/adv3Lite/manual/docs/*.md
    values:
      doc: true
      title: "{{file.basename | replace: '.md', '' }}"
      description: "{{file.basename | replace: '.md', '' }}"

collections:
  docs:
    output: true

kramdown:
  input: GFM
  extensions: [gfm]