title: TADS 3 Resources
description: The most powerful and flexible interactive fiction authoring tool, built for programmers.
incremental: true
domain: tads.dev     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://tads.dev  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
defaults:
  - scope:
      path: "docs/*.htm"
    values:
      doc: true
      title: file.name
      description: file.basename
  - scope:
      path: "docs/*.html"
    values:
      doc: true
      title: file.name
      description: file.basename