title: TADS 3 Resources
description: The most powerful and flexible interactive fiction authoring tool, built for programmers.
incremental: true
domain: tads-intfic.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://tads-intfic.github.io/tads3-website/  # the base hostname and protocol for your site, e.g. http://example.com
layout: default
defaults:
  - scope:
      path: "*.htm"
    values:
      doc: true
  - scope:
      path: "*.html"
    values:
      doc: true